### ISSUE TITLE
サンプルを用いた実践の図について

### ISSUE THREAD

**Issue by Nobu19800** [r-kurose/rtm_k8s#1]
サンプルを用いた実践の図ですが、ConsoleOutからConsoleInに矢印が伸びている部分は何を表しているのでしょうか？

**Comment by r-kurose** [comment]
データの流れのつもりでしたが、矢印が逆ですね。

**Comment by r-kurose** [comment]
ご指摘ありがとうございました。フローの間違いを修正しました。

**Comment by r-kurose** [comment]
1ヶ月以上経過したので閉じます。
