### ISSUE TITLE
IPアドレス変わりませんか？

### ISSUE THREAD

**Issue by sugarsweetrobotics** [r-kurose/rtm_k8s#2]
rtlsを送るところでIPアドレスが自分の実行環境だと変わっていたので，docker container psでIPアドレスを確認させるマニュアルを追加するとよかったかもしれません．こちらはマスターと管理PCを1台，ワーカーを1台で動作させました．

**Comment by r-kurose** [comment]
設計上はできる限り IP を調べなくて良いようにネームサーバーへのアクセスは
付録 [コンテナネットワーク](https://github.com/r-kurose/rtm_k8s/blob/master/index.md#%E3%82%B3%E3%83%B3%E3%83%86%E3%83%8A%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF) で説明しているように転送される仕組みを採用しています。
(注： 2019-12-12 に文書に合うように図の間違いを修正しました。)
なので rtls でネームサーバーにアクセスできないのは調査が必要です。
こちらでも後日に同じ環境を作って試してみます。


以下、システムの説明です。
* ネームサーバーのマニフェストファイルにIPを固定する仕込みがあります。
https://github.com/r-kurose/rtm-namaserver-image/blob/bb0b57c8411213f5157eefd4407193a18d4a0a46/nameserver.yaml#L27-L28
*  ConsoleIn は起動時のオプションでネームサーバーの位置を指定しています。
https://github.com/r-kurose/kube-simpleio-sample/blob/2f1577d60b2fa408b3b79b3acc7839330fd2f177/ConsoleIn/ConsoleIn.yaml#L20-L24

CosoleIn/ConsoleOut が正しく接続されている状況で、rtls だけがうまく動かないということの調査が必要そうです。
(単に localhost でネームサーバーが見つかっただけかもしれませんが)

**Comment by r-kurose** [comment]
同じ構成の仮想マシンを確認したところ、ネームサーバーにアクセスできました。
ネームサーバーのIPアドレスは変わりません。

ネットワークに詳しい人がやると「10.96.0.100 なんてアドレス使ってないよ」と疑問に持つので、
ドキュメントを更新してフォローしました。

**Comment by r-kurose** [comment]
1ヶ月以上経過したので閉じます。
